### ISSUE TITLE
[3.12.0] Update for new light theme

### ISSUE THREAD

**Issue by TakosThings** [TakosThings/Metro-for-Discord#114]
**What are your changes?**  
- [x] Guilds
- [x] Channels
- [x] Pinned messages popout opens in incorrect position
- [x] Recent mentions popout opens in correct position, but too low
- [x] Search popout opens in correct position, but too low
- [x] New group DM popout opens in incorrect position
- [x] Members list hover state
- [x] Context menu
- [x] Chat message options menu style, opens in incorrect position, has animation
- [x] Status changer menu
- [x] Server options menu
* Chat
  - [x] Load more messages button
  - [x] ~~New messages separator has no dividing line~~ Fixed itself
* Friends
  - [x] Add friend tab is always highlighted green
  - [x] Add friend search box container has background colour

* Issues
  - [x] ~~#107~~ - Closing, can't reproduce
  - [ ] #108
  - [x] #109
  - [ ] #111 - Update CONTRIBUTING.MD to clarify position on BD compatibility
  - [x] #112
  - [x] ~~#113~~ (This issue supersedes #113)

**Comment by TakosThings** [comment]
v3.11.3-alpha1 contains enough fixes to make the theme functional again. Get it from Releases as normal

**Comment by silent** [comment]
Line separator for new messages missing.
![image](https://user-images.githubusercontent.com/36117192/64659756-0081ae80-d403-11e9-88a3-6336333d0d69.png)

**Comment by TakosThings** [comment]
This update will instead become version 3.12.0 to allow the addition of `/components/primary/_core.scss` due to  a change in the Discord CSS.

The branch and details in this version have been updated to reflect this

**Comment by silent** [comment]
The new update changed classes again but also noticed I am unable to click on the group call chat I am in unless I go to the home directory and click on it. 
![image](https://user-images.githubusercontent.com/36117192/65366152-da6bc380-dbe5-11e9-938d-ddb63e5f24b7.png)

**Comment by TakosThings** [comment]
v3.12.0-alpha2 has been built and is available from Releases.

**Comment by silent** [comment]
Why is it like this? 
![image](https://user-images.githubusercontent.com/36117192/65367860-bb792b80-dbfd-11e9-8e0f-cb41a8451b60.png)

**Comment by TakosThings** [comment]
Not experiencing this on my end or any of my test accounts

**Comment by silent** [comment]
Sorry, looks like the cause of this is Server Folders, but if I use the previous version of Metro For Discord it doesn't show up. So I am confused on why it would show suddenly in the newer version of Metro For Discord.

**Comment by silent** [comment]
Profile Popouts and Settings are unthemed as well.

**Comment by silent** [comment]
Black colored roles in the server settings or in the member list are difficult to read
![image](https://user-images.githubusercontent.com/36117192/65451856-9f47db00-de05-11e9-9934-385cdc95cff9.png)
